name: build-and-push-docker-image

on:
    push:
        branches: ['main']
env:
    GITHUB_REGISTRY: ghcr.io
    DOCKER_IMAGE: ${{ github.repository }}

jobs:
    build-push-docker-image:
        runs-on: windows-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4
              
            - name: login to ghcr.io
              uses: docker/login-action@v3
              # run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ${{ env.GITHUB_REGISTRY }}
              with:
                registry: ${{ env.GITHUB_REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUBTOKEN }}
                
            - name: extract the metadata (tags, labels)
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.GITHUB_REGISTRY }}/${{ env.DOCKER_IMAGE }}
              
            - name: build-push-docker-image
              uses: docker/build-push-action@v5
              with:
                context: ./file
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
